(() => {
  const {t,esc,name,regions,photo,route,routeRow,duration,priceLabel}=VIATSA_UI;
  const catalog=VIATSA_CATALOG, adventures=catalog.active('adventure'), days=catalog.active('experience');
  const main=document.querySelector('main'), page=document.body.dataset.editorial;
  const sectionHead=(label,title,lead='')=>`<div class="v-section-head"><div><span class="v-kicker">${label}</span><h2>${title}</h2></div>${lead?`<p>${lead}</p>`:''}</div>`;
  const destinationList=()=>['sur','samana','norte','este'].map(region=>{
    const p=catalog.active().find(x=>x.region===region&&x.heroImage);
    return `<a class="v-dest" href="/${region==='sur'||region==='samana'?'aventuras':'experiencias'}.html?region=${region}">${photo(p.heroImage,regions[region])}<h3>${regions[region]} ↗</h3><p>${p.destinations.slice(0,4).map(esc).join(' · ')}</p></a>`;
  }).join('');
  if(page==='home'){
    document.title=t('VIATSA Travel — La otra cara de República Dominicana','VIATSA Travel — The other side of the Dominican Republic');
    main.innerHTML=`
      <section class="v-home-hero"><div class="v-container"><span class="v-kicker">${t('República Dominicana · Desde dentro','Dominican Republic · From within')}</span><h1>${t('Descubre la otra cara de República Dominicana.','Discover the other side of the Dominican Republic.')}</h1><p>${t('Caminos, mesas y paisajes compartidos con quienes conocen la isla.','Roads, tables and landscapes shared with people who know the island.')}</p><div class="v-hero-bottom"><a class="v-button" href="/aventuras.html">${t('Encuentra tu aventura','Find your adventure')} <span aria-hidden="true">↗</span></a><a class="v-link" href="/sobre-nosotros.html">${t('Conoce VIATSA','Meet VIATSA')}</a></div></div></section>
      <section class="v-section v-container"><div class="v-proposition"><div><span class="v-kicker">${t('Nuestra forma de viajar','Our way of travelling')}</span><h2>${t('No es un tour.<br>Es tu experiencia privada.','Not just a tour.<br>Your private experience.')}</h2></div><div><p>${t('No queremos que simplemente visites República Dominicana. Queremos que la vivas.','We do not want you simply to visit the Dominican Republic. We want you to experience it.')}</p><p>${t('Sentarte a la mesa. Conocer a su gente. Tomar un camino que no habías pensado recorrer. Así entendemos los viajes.','Sit down at the table. Meet the people. Take a road you had not thought of following. That is how we understand travel.')}</p></div></div></section>
      <section class="v-container" aria-label="${t('Formas de viajar','Ways to travel')}"><div class="v-ways"><a href="/experiencias.html"><strong>${t('Un día en la isla','A day on the island')} ↗</strong><span>${t('Experiencias de un día','Single-day experiences')}</span></a><a href="/aventuras.html"><strong>${t('Unos días de ruta','A few days on the road')} ↗</strong><span>${t('Aventuras de 2 a 6 días','Adventures from 2 to 6 days')}</span></a><a href="/grupales.html"><strong>${t('Un viaje compartido','A shared journey')} ↗</strong><span>${t('Salidas grupales','Group departures')}</span></a></div></section>
      <section class="v-section" id="journeys"><div class="v-container">${sectionHead(t('Tres maneras de recorrerla','Three ways to explore'),t('Rutas que Conectan','Journeys that Connect'),t('Recorre República Dominicana a través de su naturaleza, sus sabores, su cultura y, sobre todo, su gente.','Explore the Dominican Republic through its nature, its food, its culture and, above all, its people.'))}<div>${adventures.map(routeRow).join('')}</div></div></section>
      <section class="v-section v-sage" id="experiences"><div class="v-container">${sectionHead(t('Experiencias','Experiences'),t('Un día. Otra mirada a la isla.','One day. Another view of the island.'))}<div class="v-day-list">${days.filter(p=>p.featured).map(p=>`<a class="v-day-row" href="${route(p)}">${photo(p.heroImage,name(p))}<div><h3>${esc(name(p))}</h3><small>${regions[p.region]} · ${duration(p)}</small></div><span aria-hidden="true">↗</span></a>`).join('')}</div><a class="v-link" href="/experiencias.html" style="margin-top:28px">${t('Ver todas las experiencias','See all experiences')} ↗</a></div></section>
      <section class="v-section v-container"><div class="v-human">${photo('perla-16.webp',t('Viajeras en la costa sur','Travelers on the southern coast'))}<div><span class="v-kicker">${t('Las personas detrás del viaje','The people behind the journey')}</span><h2>${t('Nuestra isla.<br>Tu forma de vivirla.','Our island.<br>Your way to experience it.')}</h2><p>${t('Arisleidy y Rubén comparten una misma visión: acercarte a la República Dominicana que han recorrido y aprendido a conocer.','Arisleidy and Rubén share a vision: to introduce you to the Dominican Republic they have travelled and come to know.')}</p><ol><li>${t('Rutas que conectan naturaleza, cultura y personas.','Routes that connect nature, culture and people.')}</li><li>${t('Coordinación del viaje con un equipo local.','Trip coordination with a local team.')}</li><li>${t('Una conversación contigo antes de reservar.','A conversation with you before booking.')}</li></ol><a class="v-link" href="/sobre-nosotros.html">${t('Nuestra historia','Our story')} ↗</a></div></div></section>
      <section class="v-section v-destination-band" id="destinations"><div class="v-container">${sectionHead(t('Elige por dónde empezar','Choose where to begin'),t('Una isla, muchos caminos.','One island, many roads.'))}<div class="v-dest-list">${destinationList()}</div><a class="v-link" href="/destinos.html" style="margin-top:32px">${t('Explorar destinos','Explore destinations')} ↗</a></div></section>
      <section class="v-section v-container" id="tailor"><div class="v-tailor"><div><span class="v-kicker">${t('A tu medida','Tailor-made')}</span><h2>${t('Cuéntanos cómo<br>te gusta viajar.','Tell us how<br>you like to travel.')}</h2></div><div><p>${t('La fecha, las personas, los lugares que te llaman. Empezamos por escucharte y damos forma a la ruta contigo.','The dates, the people, the places that draw you in. We begin by listening and plan the route with you.')}</p><a class="v-button" href="/viajes-a-medida.html">${t('Diseñar mi viaje','Design my trip')} ↗</a></div></div></section>`;
  }
  if(page==='adventures'){
    document.title=t('Aventuras — VIATSA Travel','Adventures — VIATSA Travel');
    main.innerHTML=`<section class="v-container v-page-intro"><span class="v-kicker">${t('Rutas privadas · República Dominicana','Private routes · Dominican Republic')}</span><h1>${t('Tómate unos días.<br>Conoce la otra cara.','Take a few days.<br>See the other side.')}</h1><p>${t('Del sur a Samaná, o una vuelta por la isla. Tres rutas para viajar entre playas, pueblos y agua dulce.','From the south to Samaná, or around the island. Three routes through beaches, towns and freshwater landscapes.')}</p><div class="v-filters" aria-label="${t('Región','Region')}">${['todas','sur','samana'].map(r=>`<button type="button" data-region="${r}" aria-pressed="false">${regions[r]}</button>`).join('')}</div><p class="v-count" role="status"></p></section><section class="v-container v-section" style="padding-top:0" id="adventure-list" aria-label="${t('Aventuras','Adventures')}"></section>`;
    const draw=region=>{
      const products=adventures.filter(p=>region==='todas'||p.region===region);
      main.querySelector('#adventure-list').innerHTML=products.map(routeRow).join('');
      main.querySelector('.v-count').textContent=products.length+' '+t('rutas para explorar','routes to explore');
      main.querySelectorAll('[data-region]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.region===region)));
    };
    const region=new URLSearchParams(location.search).get('region');draw(['sur','samana'].includes(region)?region:'todas');
    main.querySelector('.v-filters').onclick=e=>{const b=e.target.closest('[data-region]');if(b)draw(b.dataset.region)};
  }
  if(page==='destinations'){
    document.title=t('Destinos — VIATSA Travel','Destinations — VIATSA Travel');
    main.innerHTML=`<section class="v-container v-page-intro"><span class="v-kicker">${t('Geografía de un viaje','The geography of a journey')}</span><h1>${t('¿Qué parte de la isla<br>quieres vivir?','Which part of the island<br>will you experience?')}</h1><p>${t('La costa del sur, las cascadas de Samaná, los pueblos del norte y las islas del este. Sigue el paisaje que te llama.','The southern coast, Samaná’s waterfalls, northern towns and eastern islands. Follow the landscape that draws you in.')}</p></section><section class="v-container v-section" style="padding-top:0"><div class="v-dest-list">${destinationList()}</div></section><section class="v-sage v-section"><div class="v-container v-tailor"><h2>${t('¿Más de un destino?','More than one destination?')}</h2><div><p>${t('Podemos diseñar una ruta que conecte los lugares que quieres conocer.','We can plan a route connecting the places you would like to see.')}</p><a class="v-button" href="/viajes-a-medida.html">${t('Diseñar mi viaje','Design my trip')} ↗</a></div></div></section>`;
  }
})();
