/* Shared navigation and footer, including legacy catalogue pages. */
document.addEventListener('DOMContentLoaded',()=>{
const en=document.documentElement.lang==='en'||localStorage.getItem('viatsa-lang')==='en';
const t=(es,english)=>en?english:es;
document.querySelectorAll('header a').forEach(a=>{if(/^(Sobre Viatsa|About Viatsa|Sobre nosotros|About us)$/i.test(a.textContent.trim()))a.remove()});
document.querySelectorAll('a').forEach(a=>{const label=a.textContent.trim();if(/diseñ|design.*trip|a tu medida|tailor-made|crear un viaje/i.test(label)||a.getAttribute('href')==='#tailor'||a.getAttribute('href')==='index.html#tailor')a.href='viajes-a-medida.html'});
const footer=document.querySelector('footer');
if(footer){footer.className='site-footer';footer.innerHTML=`<div class="site-footer-inner"><div><a href="index.html"><img src="brand-logo-white.png?v=1" alt="VIATSA TRAVEL" width="230"></a><p>VIATSA TRAVEL<br>${t('Santo Domingo, República Dominicana','Santo Domingo, Dominican Republic')}</p><a href="https://wa.me/18099723232" target="_blank" rel="noopener">WhatsApp · +1 809 972 3232</a><a href="mailto:viatsatravel@gmail.com">Email · viatsatravel@gmail.com</a><a href="https://instagram.com/viatsa.travel" target="_blank" rel="noopener">Instagram</a></div><nav aria-label="${t('Viajes','Trips')}"><a href="aventuras.html">${t('Aventuras','Adventures')}</a><a href="experiencias.html">${t('Experiencias','Experiences')}</a><a href="grupales.html">${t('Excursiones grupales','Group excursions')}</a><a href="viajes-a-medida.html">${t('Viajes a medida','Tailor-made trips')}</a><a href="travel-partners.html">Travel Partners</a></nav><nav aria-label="${t('Información','Information')}"><a href="sobre-nosotros.html">${t('Sobre nosotros','About us')}</a><a href="preguntas-frecuentes.html">${t('Preguntas frecuentes','Frequently asked questions')}</a><a href="terminos.html">${t('Términos y condiciones','Terms and conditions')}</a><a href="privacidad.html">${t('Política de privacidad','Privacy policy')}</a></nav></div><div class="site-footer-bottom">© ${new Date().getFullYear()} VIATSA TRAVEL</div>`}
const css=document.createElement('style');css.textContent='.site-footer{background:#606042!important;color:#fff!important;padding:56px 20px 28px;font:14px/1.65 Arial,sans-serif}.site-footer-inner{max-width:1220px;margin:auto;display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:40px}.site-footer img{display:block;max-width:100%;height:auto}.site-footer a{display:block;color:#fff!important;text-decoration:none;margin:0 0 12px;overflow-wrap:anywhere}.site-footer a:hover{text-decoration:underline}.site-footer nav{display:block;height:auto;border:0;padding:0;background:none}.site-footer p{color:white}.site-footer-bottom{max-width:1220px;margin:30px auto 0;padding-top:22px;border-top:1px solid #ffffff45}.site-footer a:focus-visible{outline:2px solid #FFECD2;outline-offset:5px}@media(max-width:700px){.site-footer-inner{grid-template-columns:1fr;gap:26px}}';document.head.append(css);
});
