const PRODUCTS={'entre-cascadas-y-palmeras':{fixed:42200,variable:4500,max:4},'vuelta-a-la-isla':{fixed:77200,variable:9100,max:4}};
const TRANSPORT=[{max:4,cents:13300,label:'Vehículo privado'},{max:10,cents:45200,label:'Transporte para grupo'},{max:28,cents:61400,label:'Autobús'}];
const TENTS={double:{capacity:2,cents:8000,label:'Tienda para 2 personas'},quadruple:{capacity:4,cents:12000,label:'Tienda para 4 personas'},sextuple:{capacity:6,cents:17000,label:'Tienda para 6 personas'}};
const BOATS=[{capacity:5,cents:6800},{capacity:10,cents:8500},{capacity:13,cents:10200}];
function boatPlan(n){let best=null,max=Math.ceil(n/5)+1;for(let a=0;a<=max;a++)for(let b=0;b<=max;b++)for(let c=0;c<=max;c++){const capacity=a*5+b*10+c*13;if(capacity<n)continue;const candidate={cost:a*6800+b*8500+c*10200,count:a+b+c};if(!best||candidate.cost<best.cost)best=candidate}return best}
function calculate(body={}){const travelers=Number(body.travelers),productId=String(body.productId||'');if(!Number.isSafeInteger(travelers)||travelers<1)return{status:'invalid',message:'Revisa la cantidad de viajeros.'};let cost,transport='',accommodation=[],activity='';
if(productId==='perla-del-sur'){const vehicle=TRANSPORT.find(x=>travelers<=x.max);if(!vehicle)return{status:'quote_required',message:'Este grupo requiere una cotización personalizada.'};let capacity=0,lodging=0;for(const[id,o]of Object.entries(TENTS)){const quantity=Number((body.accommodation||{})[id]||0);if(!Number.isSafeInteger(quantity)||quantity<0)return{status:'invalid',message:'Revisa el hospedaje.'};capacity+=quantity*o.capacity;lodging+=quantity*o.cents;if(quantity)accommodation.push({id,label:o.label,quantity,capacity:o.capacity})}if(capacity<travelers)return{status:'incomplete',message:`Te faltan plazas para ${travelers-capacity} personas.`,capacity};const boats=boatPlan(travelers);cost=vehicle.cents+10000+2500*travelers+lodging+boats.cost;transport=vehicle.label;activity=`Embarcaciones necesarias para tu grupo: ${boats.count}`}
else{const c=PRODUCTS[productId];if(!c||travelers>c.max)return{status:'quote_required',message:'Este grupo requiere una cotización personalizada.'};cost=c.fixed+c.variable*travelers;transport='Vehículo privado'}
const retailPrice=Math.round(cost*2.3),deposit=Math.round(retailPrice*.5);let balanceDueDate=null;if(body.date){const d=new Date(body.date+'T12:00:00Z');if(!Number.isNaN(d.valueOf())){d.setUTCDate(d.getUTCDate()-3);balanceDueDate=d.toISOString().slice(0,10)}}return{status:'calculated',currency:'USD',productId,travelers,pickup:'Santo Domingo',transport,accommodation,activity,date:body.date||'',retailPrice,deposit,remainingBalance:retailPrice-deposit,balanceDueDate}}
module.exports=function(req,res){if(req.method!=='POST')return res.status(405).json({status:'invalid',message:'Método no permitido.'});try{return res.status(200).json(calculate(req.body))}catch{return res.status(400).json({status:'invalid',message:'No pudimos procesar la cotización.'})}};module.exports.calculate=calculate;
